apiVersion: apps/v1
kind: Deployment
metadata:
 name: ekor-deployment
spec:
 selector:
   matchLabels:
     run: ekor-deployment
 replicas: 1
 template:
   metadata:
     labels:
       run: ekor-deployment
   spec:
     containers:
     - name: ekor-deployment
       image: $ECR_REPO_URL/$DOCKER_IMAGE_VERSION
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 100m
         requests:
           cpu: 50m
