apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ekor-hpa-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ekor-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5
  
