---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: ekor-deployment
spec:
 selector:
   matchLabels:
     run: ekor-deployment
 replicas: 2
 template:
   metadata:
     labels:
       run: ekor-deployment
   spec:
     containers:
     - name: ekor-deployment
       image: $ECR_REPO_URL/$DOCKER_IMAGE_VERSION
       ports:
       - containerPort: 80
       resources:
         #limits:
          # cpu: 500m
         #requests:
          # cpu: 200m
---
---         
apiVersion: v1
kind: Service
metadata:
  name: ekor-deployment-svc
  labels:
    run: ekor-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    run: ekor-deployment
---   
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ekor-hpa-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ekor-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5
---
